package net.cloudedarctrooper.templar_addons_mod.core;

import net.cloudedarctrooper.templar_addons_mod.item.TKTAItems;
import net.minecraft.world.item.Item;

public interface TKTAItemDefs {

    Item MANA_SHARDS = TKTAItems.MANA_SHARDS.get();
    Item RAW_MANA = TKTAItems.RAW_MANA.get();
    Item CRUDE_MANA = TKTAItems.CRUDE_MANA.get();
    Item CUT_MANA = TKTAItems.CUT_MANA.get();
    Item FLAWLESS_MANA = TKTAItems.FLAWLESS_MANA.get();
    Item RAW_SILVER = TKTAItems.RAW_SILVER.get();
    Item SILVER_INGOT = TKTAItems.SILVER_INGOT.get();
    Item INFUSED_SILVER_INGOT = TKTAItems.INFUSED_SILVER_INGOT.get();
    Item RAW_ELECTRIC_AMALGAM = TKTAItems.RAW_ELECTRIC_AMALGAM.get();
    Item ELECTRUM_MIX = TKTAItems.ELECTRUM_MIX.get();
    Item RAW_ELECTRUM = TKTAItems.RAW_ELECTRUM.get();
    Item ELECTRUM_INGOT = TKTAItems.ELECTRUM_INGOT.get();
    Item INFUSED_ELECTRUM_INGOT = TKTAItems.INFUSED_ELECTRUM_INGOT.get();
    Item BLACK_MANA = TKTAItems.BLACK_MANA.get();
    Item END_MANA = TKTAItems.END_MANA.get();
    Item CONCENTRATED_MANA_BUCKET = TKTAItems.CONCENTRATED_MANA_BUCKET.get();
    Item LEATHER_TANNIN = TKTAItems.LEATHER_TANNIN.get();
    Item TOUGHENED_LEATHER = TKTAItems.TOUGHENED_LEATHER.get();
    Item CUT_LEATHER = TKTAItems.CUT_LEATHER.get();
    Item LEATHER_STRAP = TKTAItems.LEATHER_STRAP.get();
    Item TOUGHENED_LEATHER_STRAP = TKTAItems.TOUGHENED_LEATHER_STRAP.get();
    Item GRIND_SURFACE_SAND = TKTAItems.GRIND_SURFACE_SAND.get();
    Item GRIND_SURFACE_FLINT = TKTAItems.GRIND_SURFACE_FLINT.get();
    Item GRIND_SURFACE_BLAST_STONE = TKTAItems.GRIND_SURFACE_BLAST_STONE.get();
    Item GRIND_SURFACE_OBSIDIAN = TKTAItems.GRIND_SURFACE_OBSIDIAN.get();
    Item GRIND_SURFACE_NETHER = TKTAItems.GRIND_SURFACE_NETHER.get();
    Item GRIND_SURFACE_QUARTZ = TKTAItems.GRIND_SURFACE_QUARTZ.get();
    Item GRIND_SURFACE_BLAZED = TKTAItems.GRIND_SURFACE_BLAZED.get();
    Item GRIND_SURFACE_PURPUR = TKTAItems.GRIND_SURFACE_PURPUR.get();
    Item GRIND_SURFACE_NETHERITE = TKTAItems.GRIND_SURFACE_NETHERITE.get();
    Item GRIND_SURFACE_ENDERITE = TKTAItems.GRIND_SURFACE_ENDERITE.get();
    Item LOCKED_STARTER_BOOK = TKTAItems.LOCKED_STARTER_BOOK.get();
    Item GUIDE_BOOK = TKTAItems.GUIDE_BOOK.get();

}
